// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJzBLh-ZyfgkstvXLWtBH9e_15Z-zaQUo',
    appId: '1:45617888402:web:675980212ca652e4257a4b',
    messagingSenderId: '45617888402',
    projectId: 'tabarno-5ae28',
    authDomain: 'tabarno-5ae28.firebaseapp.com',
    storageBucket: 'tabarno-5ae28.firebasestorage.app',
    measurementId: 'G-ERT3L0SNJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUibolivJsKy7i5kuOy_o9UJd771GK6lU',
    appId: '1:45617888402:android:8842372f1334690e257a4b',
    messagingSenderId: '45617888402',
    projectId: 'tabarno-5ae28',
    storageBucket: 'tabarno-5ae28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7NtVGbxuh-ujTlDp1qoNttca6OIMXHDY',
    appId: '1:45617888402:ios:4b826fd640ce26f5257a4b',
    messagingSenderId: '45617888402',
    projectId: 'tabarno-5ae28',
    storageBucket: 'tabarno-5ae28.firebasestorage.app',
    iosBundleId: 'com.example.quiz31',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7NtVGbxuh-ujTlDp1qoNttca6OIMXHDY',
    appId: '1:45617888402:ios:4b826fd640ce26f5257a4b',
    messagingSenderId: '45617888402',
    projectId: 'tabarno-5ae28',
    storageBucket: 'tabarno-5ae28.firebasestorage.app',
    iosBundleId: 'com.example.quiz31',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJzBLh-ZyfgkstvXLWtBH9e_15Z-zaQUo',
    appId: '1:45617888402:web:b7c0a9797dba0ee8257a4b',
    messagingSenderId: '45617888402',
    projectId: 'tabarno-5ae28',
    authDomain: 'tabarno-5ae28.firebaseapp.com',
    storageBucket: 'tabarno-5ae28.firebasestorage.app',
    measurementId: 'G-2BF1HN0RFS',
  );
}
